export const SET_SCENE_ORIENTATION = "SET_SCENE_ORIENTATION";
export const SET_SCENE_LOADED = "SET_SCENE_LOADED";
export const RESET_TO_INITAL_STATE = "RESET_TO_INITAL_STATE";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
