SELECT
EMPLOYEES.NAME, EMPLOYEE_PAN.UIN
FROM EMPLOYEES INNER JOIN EMPLOYEE_PAN
ON EMPLOYEES.ID = EMPLOYEE_PAN.ID;





SELECT 
CONCAT(DEPARTMENTS.DEPT_NAME, " " ,COUNT(STUDENTS.STUDENT_ID))
FROM STUDENTS INNER JOIN DEPARTMENTS
ON STUDENTS.DEPT_ID = DEPARTMENTS.DEPT_ID
GROUP BY DEPARTMENTS.DEPT_ID
ORDER BY COUNT(STUDENTS.STUDENT_ID) DESC, DEPARTMENTS.DEPT_NAME ASC;